using System.Net.Http.Headers;
using System.Net.Http.Json;
using Microsoft.Extensions.Options;
using ShippingPlatform.Application.Interfaces;

namespace ShippingPlatform.Infrastructure.D365;

/// <summary>
/// D365 Finance &amp; Supply Chain Management integration client using the standard Data
/// Entities / OData API (BR-060–062). Wrapped with a resilience pipeline (retry + circuit
/// breaker) registered in DependencyInjection so transient D365 failures don't cascade into the
/// shipping platform (System Overview §6.3).
/// </summary>
public class D365IntegrationClient : ID365IntegrationClient
{
    private readonly HttpClient _httpClient;
    private readonly ID365AuthTokenProvider _tokenProvider;
    private readonly D365ClientOptions _options;

    public D365IntegrationClient(HttpClient httpClient, ID365AuthTokenProvider tokenProvider, IOptions<D365ClientOptions> options)
    {
        _httpClient = httpClient;
        _tokenProvider = tokenProvider;
        _options = options.Value;
    }

    public async Task<D365OrderDto?> GetOrderAsync(string orderReference, CancellationToken ct = default)
    {
        await AuthorizeAsync(ct);
        // SalesOrderHeaders is the standard D365 F&SCM Data Entity for sales order headers.
        var response = await _httpClient.GetAsync(
            $"{_options.ODataPath}/SalesOrderHeaders?$filter=SalesOrderNumber eq '{Uri.EscapeDataString(orderReference)}'", ct);

        if (!response.IsSuccessStatusCode)
        {
            return null;
        }

        var payload = await response.Content.ReadFromJsonAsync<D365ODataResponse<D365OrderDto>>(cancellationToken: ct);
        return payload?.Value.FirstOrDefault();
    }

    public async Task<D365AddressDto?> GetCustomerAddressAsync(string customerAccount, CancellationToken ct = default)
    {
        await AuthorizeAsync(ct);
        var response = await _httpClient.GetAsync(
            $"{_options.ODataPath}/CustomerAddresses?$filter=CustomerAccount eq '{Uri.EscapeDataString(customerAccount)}'", ct);

        if (!response.IsSuccessStatusCode)
        {
            return null;
        }

        var payload = await response.Content.ReadFromJsonAsync<D365ODataResponse<D365AddressDto>>(cancellationToken: ct);
        return payload?.Value.FirstOrDefault();
    }

    public async Task PostBillingEventAsync(D365BillingEventDto billingEvent, CancellationToken ct = default)
    {
        await AuthorizeAsync(ct);
        // FreeTextInvoiceHeaders (or the customer's preferred billing entity) receives the
        // freight/service charge generated by the shipping platform (BR-061, D365's
        // "very high" feasibility billing capability).
        var response = await _httpClient.PostAsJsonAsync($"{_options.ODataPath}/FreeTextInvoiceHeaders", billingEvent, ct);
        response.EnsureSuccessStatusCode();
    }

    public async Task PostInventoryEventAsync(D365InventoryEventDto inventoryEvent, CancellationToken ct = default)
    {
        await AuthorizeAsync(ct);
        var response = await _httpClient.PostAsJsonAsync($"{_options.ODataPath}/InventoryJournalTransLines", inventoryEvent, ct);
        response.EnsureSuccessStatusCode();
    }

    private async Task AuthorizeAsync(CancellationToken ct)
    {
        var token = await _tokenProvider.GetAccessTokenAsync(ct);
        _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
    }

    private class D365ODataResponse<T>
    {
        public List<T> Value { get; set; } = new();
    }
}
